/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:435410:
  appc.background(230);
} //_CODE_:window1:435410:

public void reset_button(GButton source, GEvent event) { //_CODE_:Reset:320841:
  println("Reset - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Reset:320841:

public void pause_button(GButton source, GEvent event) { //_CODE_:Pause:665394:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Pause:665394:

public void time_slider(GSlider source, GEvent event) { //_CODE_:fastforwards:613240:
  println("fastforwards - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:fastforwards:613240:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:543297:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:543297:

public void colorList1_drop(GDropList source, GEvent event) { //_CODE_:colorList1:422464:
  println("colorList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:colorList1:422464:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:235858:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield2:235858:

public void colorList2_drop(GDropList source, GEvent event) { //_CODE_:colorList2:817056:
  println("colorList2 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:colorList2:817056:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 500, 800, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  Reset = new GButton(window1, 58, 13, 80, 30);
  Reset.setText("Reset");
  Reset.setLocalColorScheme(GCScheme.RED_SCHEME);
  Reset.addEventHandler(this, "reset_button");
  Pause = new GButton(window1, 199, 12, 80, 30);
  Pause.setText("Pause");
  Pause.addEventHandler(this, "pause_button");
  fastforwards = new GSlider(window1, 332, 15, 122, 52, 10.0);
  fastforwards.setShowLimits(true);
  fastforwards.setLimits(1, 1, 3);
  fastforwards.setNbrTicks(3);
  fastforwards.setStickToTicks(true);
  fastforwards.setShowTicks(true);
  fastforwards.setEasing(5.0);
  fastforwards.setNumberFormat(G4P.INTEGER, 0);
  fastforwards.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  fastforwards.setOpaque(false);
  fastforwards.addEventHandler(this, "time_slider");
  timelabel = new GLabel(window1, 344, 6, 89, 24);
  timelabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  timelabel.setText("Fast Forward");
  timelabel.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  timelabel.setOpaque(true);
  lline1 = new GLabel(window1, 234, 62, 7, 208);
  lline1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lline1.setText("| | | | | | | | | | | |");
  lline1.setOpaque(false);
  line2 = new GLabel(window1, 233, 205, 8, 231);
  line2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  line2.setText("| | | | | | | | | |");
  line2.setOpaque(false);
  label1 = new GLabel(window1, 61, 65, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Home Team");
  label1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label1.setOpaque(false);
  team2 = new GLabel(window1, 341, 77, 80, 20);
  team2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  team2.setText("Away Team");
  team2.setOpaque(false);
  name1 = new GLabel(window1, 2, 92, 80, 20);
  name1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  name1.setText("Name");
  name1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  name1.setOpaque(false);
  textfield1 = new GTextField(window1, 2, 116, 120, 30, G4P.SCROLLBARS_NONE);
  textfield1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  color1name = new GLabel(window1, 142, 93, 80, 20);
  color1name.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  color1name.setText("Color");
  color1name.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  color1name.setOpaque(false);
  colorList1 = new GDropList(window1, 135, 121, 90, 60, 2, 10);
  colorList1.setItems(loadStrings("list_422464"), 0);
  colorList1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  colorList1.addEventHandler(this, "colorList1_drop");
  name2label = new GLabel(window1, 247, 100, 80, 20);
  name2label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  name2label.setText("Name");
  name2label.setOpaque(false);
  c2 = new GLabel(window1, 394, 102, 80, 20);
  c2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  c2.setText("Color");
  c2.setOpaque(false);
  textfield2 = new GTextField(window1, 244, 123, 133, 34, G4P.SCROLLBARS_NONE);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  colorList2 = new GDropList(window1, 392, 129, 90, 60, 2, 10);
  colorList2.setItems(loadStrings("list_817056"), 0);
  colorList2.addEventHandler(this, "colorList2_drop");
  skilll1 = new GLabel(window1, 63, 163, 80, 20);
  skilll1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  skilll1.setText("Skills");
  skilll1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  skilll1.setOpaque(false);
  label2 = new GLabel(window1, 330, 167, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Skills");
  label2.setOpaque(false);
  shooting1 = new GLabel(window1, 20, 197, 80, 20);
  shooting1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  shooting1.setText("Shooting");
  shooting1.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton Reset; 
GButton Pause; 
GSlider fastforwards; 
GLabel timelabel; 
GLabel lline1; 
GLabel line2; 
GLabel label1; 
GLabel team2; 
GLabel name1; 
GTextField textfield1; 
GLabel color1name; 
GDropList colorList1; 
GLabel name2label; 
GLabel c2; 
GTextField textfield2; 
GDropList colorList2; 
GLabel skilll1; 
GLabel label2; 
GLabel shooting1; 
